push

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -7,13 +7,46 @@ on:
     branches:
       - main
 env:
-  MIRROR_URL: git@github.com:CestAberrant/devops.git
+  MIRROR_URL: git@github.com:EpitechPromo2028/B-DOP-200-RUN-2-1-chocolatine-matheo.moinache.git
 
 jobs:
-  checkout:
+    check_coding_style:
+    runs-on: ubuntu-latest
+    container:
+      image: ghcr.io/epitech/coding-style-checker:latest
+    steps:
+      - name: checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: run coding style
+        run: check.sh $(pwd) $(pwd)
+      - name: Check if there are errors
+        run: |
+            if [ -g coding-style-reports.log]; then
+                echo "Error coding-style"
+                exit 1
+            fi
+
+    check_program_compilation:
+    needs: check_coding_style
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - name: checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: make
+        run: make
+      - name: make clean
+        run: make cleean
+
+  push_to_mirror:
+    needs: [check_coding_style, check_program_compilation]
+    runs-on: ubuntu-latest
+    steps:
+      - name: checkout
+        uses: actions/checkout@v4
         with:
           fetch-depth: 0
       - uses: pixta-dev/repository-mirroring-action@v1
@@ -22,5 +55,4 @@ jobs:
             ${{ env.MIRROR_URL }}
           ssh_private_key:
             ${{ secrets.GIT_SSH_PRIVATE_KEY}}
-  
 
